# Generated by Django 4.2.5 on 2023-09-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('customer', 'customer'), ('admin', 'admin')], default='user', max_length=50),
        ),
    ]
