# Generated by Django 4.2.4 on 2023-09-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_album_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('album_name', 'artist'), name='unique_album'),
        ),
    ]
