# Generated by Django 4.2.4 on 2023-08-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.CharField(max_length=5),
        ),
    ]
